#cloud-config

runcmd:
  - apt-get update
  - curl -fsSL https://get.docker.com | sh
  - apt-get install podman -y
  - >-
    add-apt-repository ppa:git-core/ppa --yes --update && apt-get install git
    --yes
  - curl -O https://storage.googleapis.com/golang/go1.20.1.linux-amd64.tar.gz
  - tar -xvf go1.20.1.linux-amd64.tar.gz
  - sudo cp -r go /usr/local
  - sudo mv go /root
  - echo "export GOROOT=/usr/local/go" >> /root/.profile
  - echo "export GOPATH=$HOME/go" >> /root/.profile
  - echo "export PATH=$GOPATH/bin:$GOROOT/bin:$PATH" >> /root/.profile
  - source /root/.profile
  - apt install -y build-essential
  - sudo apt install rustc -y
  - git clone https://github.com/firecracker-microvm/firecracker
  - ARCH="$(uname -m)"
  - sudo ./firecracker/tools/devtool --unattended build
  - sudo cp ./firecracker/build/cargo_target/${ARCH}-unknown-linux-musl/debug/firecracker /usr/bin
  - sudo cp ./firecracker/build/cargo_target/${ARCH}-unknown-linux-musl/debug/jailer /usr/bin
  - sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
  - git clone https://github.com/quarksgroup/sparkd.git
  - task all -d sparkd
