#cloud-config

runcmd:
  - apt-get update
  - curl -fsSL https://get.docker.com | sh
  - apt-get install podman -y
  - echo " " >> /etc/containers/registries.conf
  - echo "# Allow to use docker.io as default registry" >> /etc/containers/registries.conf
  - echo "unqualified-search-registries = [\"docker.io\"]" >> /etc/containers/registries.conf
  - add-apt-repository ppa:git-core/ppa -y --update && apt-get install git -y
  - curl -O https://storage.googleapis.com/golang/go1.20.1.linux-amd64.tar.gz
  - tar -xvf go1.20.1.linux-amd64.tar.gz
  - cp -r go /usr/local
  - mv go /root
  - echo "export GOROOT=/usr/local/go" >> $HOME/.profile
  - echo "export GOPATH=$HOME/go" >> $HOME/.profile
  - source $HOME/.profile
  - echo "export PATH=$GOPATH/bin:$GOROOT/bin:$PATH" >> $HOME/.profile
  - source $HOME/.profile
  - apt install -y build-essential
  - apt install rustc -y
  - git clone https://github.com/firecracker-microvm/firecracker
  - ARCH="$(uname -m)"
  - ./firecracker/tools/devtool --unattended build
  - cp ./firecracker/build/cargo_target/${ARCH}-unknown-linux-musl/debug/firecracker /usr/bin
  - cp ./firecracker/build/cargo_target/${ARCH}-unknown-linux-musl/debug/jailer /usr/bin
  - sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
  - git clone https://github.com/quarksgroup/sparkd.git
  - cd /sparkd
  - task all
  - nohup ./bin &
